import { KnowledgeBaseInfo, FolderInfo, KnowledgeFile, TrashItem } from "./knowledge-types";

export const mockKnowledgeBases: KnowledgeBaseInfo[] = [
  {
    knowledge_base_id: "kb-legal",
    knowledge_base_name: "公司法务共享库",
    knowledge_type: "common_file",
    description: "合同模板、合规制度、法务指引",
  },
  {
    knowledge_base_id: "kb-tech",
    knowledge_base_name: "技术文档库",
    knowledge_type: "common_file",
    description: "架构设计、研发规范、运维手册",
  },
  {
    knowledge_base_id: "kb-product",
    knowledge_base_name: "产品需求文档",
    knowledge_type: "common_file",
    description: "PRD、用户调研、竞品分析",
  },
];

export const mockFolders: FolderInfo[] = [
  {
    folder_id: "folder-root-legal",
    folder_name: "合同模板",
    full_path: "/合同模板",
    parent_folder_id: null,
    depth: 0,
    knowledge_base_id: "kb-legal",
  },
  {
    folder_id: "folder-legal-1",
    folder_name: "劳动合同",
    full_path: "/合同模板/劳动合同",
    parent_folder_id: "folder-root-legal",
    depth: 1,
    knowledge_base_id: "kb-legal",
  },
  {
    folder_id: "folder-legal-2",
    folder_name: "保密协议",
    full_path: "/合同模板/保密协议",
    parent_folder_id: "folder-root-legal",
    depth: 1,
    knowledge_base_id: "kb-legal",
  },
  {
    folder_id: "folder-root-tech",
    folder_name: "架构设计",
    full_path: "/架构设计",
    parent_folder_id: null,
    depth: 0,
    knowledge_base_id: "kb-tech",
  },
  {
    folder_id: "folder-tech-1",
    folder_name: "微服务",
    full_path: "/架构设计/微服务",
    parent_folder_id: "folder-root-tech",
    depth: 1,
    knowledge_base_id: "kb-tech",
  },
  {
    folder_id: "folder-root-product",
    folder_name: "需求调研",
    full_path: "/需求调研",
    parent_folder_id: null,
    depth: 0,
    knowledge_base_id: "kb-product",
  },
];

export const mockFiles: KnowledgeFile[] = [
  {
    file_id: "file-1",
    file_name: "标准合同范本2023版.pdf",
    folder_id: "folder-root-legal",
    file_size: 2355200,
    mime_type: "application/pdf",
    knowledge_base_id: "kb-legal",
    description: "适用于常规采购与服务合同",
    updated_at: "2026-03-08T10:20:00+08:00",
    index_status: "success",
    progress: 1,
  },
  {
    file_id: "file-2",
    file_name: "法律合规指南.pdf",
    folder_id: "folder-legal-2",
    file_size: 1880000,
    mime_type: "application/pdf",
    knowledge_base_id: "kb-legal",
    description: "重点条款与合规检查清单",
    updated_at: "2026-03-07T15:40:00+08:00",
    index_status: "processing",
    progress: 0.52,
  },
  {
    file_id: "file-3",
    file_name: "知识产权保护条款.docx",
    folder_id: "folder-root-legal",
    file_size: 468000,
    mime_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    knowledge_base_id: "kb-legal",
    description: "知识产权相关条款合集",
    updated_at: "2026-03-06T09:10:00+08:00",
    index_status: "pending",
    progress: 0,
  },
  {
    file_id: "file-4",
    file_name: "微服务设计规范.pdf",
    folder_id: "folder-tech-1",
    file_size: 1260000,
    mime_type: "application/pdf",
    knowledge_base_id: "kb-tech",
    description: "服务拆分与接口约定",
    updated_at: "2026-03-09T08:00:00+08:00",
    index_status: "success",
    progress: 1,
  },
  {
    file_id: "file-5",
    file_name: "系统稳定性治理方案.pdf",
    folder_id: "folder-root-tech",
    file_size: 980000,
    mime_type: "application/pdf",
    knowledge_base_id: "kb-tech",
    description: "故障演练与稳定性指标",
    updated_at: "2026-03-05T14:05:00+08:00",
    index_status: "failed",
    progress: 0.14,
  },
  {
    file_id: "file-6",
    file_name: "用户访谈摘要.md",
    folder_id: "folder-root-product",
    file_size: 56000,
    mime_type: "text/markdown",
    knowledge_base_id: "kb-product",
    description: "2026年第一季度访谈结论",
    updated_at: "2026-03-09T19:30:00+08:00",
    index_status: "success",
    progress: 1,
  },
];

export const mockTrashItems: TrashItem[] = [
  {
    item_type: "file",
    item_id: "file-trash-1",
    item_name: "历史合同备份.zip",
    file_size: 3650000,
    knowledge_base_id: "kb-legal",
    deleted_at: "2026-03-06T11:00:00+08:00",
  },
  {
    item_type: "folder",
    item_id: "folder-trash-1",
    item_name: "旧版需求",
    full_path: "/需求调研/旧版需求",
    knowledge_base_id: "kb-product",
    deleted_at: "2026-03-02T17:20:00+08:00",
  },
];
